name: WARP_env
channels:
  - conda-forge
  - defaults
dependencies:
  # Python-Version (ggf. anpassen)
  - python=3.12

  # Pakete, die über conda installiert werden
  - pyqt=5        # entspricht pyqt5
  - pyqtgraph
  - matplotlib
  - pandas
  
  - scikit-learn  # statt "sklearn" (korrekter conda/pip-Name)
  - scipy

  # Wichtig: pip selbst muss als Abhängigkeit aufgeführt sein,
  # damit conda die pip-Installation korrekt durchführt
  - pip

  # Pakete, die explizit über pip installiert werden sollen
  - pip:
    - numpy
    - pyopenms
    - seaborn
